### ISSUE TITLE
Pixel density should be forced to 1

### ISSUE THREAD

**Issue by skeswa** [CodyJamesCasey/ghost-pepper#5]
Scales with the client display currently

**Comment by YurkaninRyan** [comment]
Working on this issue now.

**Comment by YurkaninRyan** [comment]
Potentially fixed in latest push

**Comment by skeswa** [comment]
Not fixed, but I'm not sure we can even fix this :. `WebGLRenderer` kind of forces the issue.
